server:
  port: 8282

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate: error
    com:
      lindaring:
        base: debug

spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?useSSL=false&serverTimezone=CAT
    username: root
    password: 211021555
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
